### ISSUE TITLE
[Bug] Compatibility with storybook 6.4.x

### ISSUE THREAD

**Issue by stuartizon** [storybook-community/addon-queryparams#2]
### Describe the bug

Is this latest version expected to work with storybook 6.4.x? We have storybook 6.4.14 in our repo with version 6.2.9 (the latest) of addon-queryparams. The query params don't seem to be passing through to the source component.

All was working fine until we upgraded storybook. Previous version we were using was 6.3.12

### Steps to reproduce the behavior

1. Installed versions as above ⬆️ 
2. Added a decorator like this in the storybook preview file

```
const localeDecorator = (Story, context) => {
    useEffect(() => {
        addParameters({query: {locale: "en-NZ"}});
        forceReRender();
    });

    return <Story/> ;
};

export const decorators = [localeDecorator];
```

3. Create a source component which writes out the locale e.g. to the console, and create a simply story for it

### Expected behaviour
en-NZ is written to the console

### Environment
 - OS: Mac
 - Node.js version: 14.17.0
 - NPM version: 6.14.13
 - Browser (if applicable): chrome
 - Browser version (if applicable): 96.0.4664.110

**Comment by florinpavel22** [comment]
Bumping this.

**Comment by withintheruins14** [comment]
I don't think this addon works with the current release, happy to post code but it's all very boilerplate

**Comment by yannbf** [comment]
Hey peeps, please upgrade your Storybook to either version 7 or 8, and the addon to version 7.0.0, which is compatible with both Storybook 7 and 8. Thanks!
