### ISSUE TITLE
[Bug] Not Mocking for Next.js `useSearchParams`

### ISSUE THREAD

**Issue by JesseKuntz** [storybook-community/addon-queryparams#9]
### Describe the bug

When accessing the query params through `useSearchParams` from `next/navigation`, the config:

```
parameters: {
  query: {
    name: "name"
  }
}
```

Does not work.

### Steps to reproduce the behavior

I'm installing and adding `@storybook/addon-queryparams` to the `addons` array in `main.ts`, and then using the `query` parameter to set the URL query param, but component running in the story can't pick it up.

### Expected behavior

The query param is used correctly in the component rendered in the story. In this case, it should be shown on the page, just as it is when running the Next.js app locally.

### Environment

 - OS: [Mac OSX]
 - Node.js version: [v18.19.0]
 - NPM version: [10.2.3]
 - Browser (if applicable): [chrome]
 - Browser version (if applicable): [122.0.6261.112]

### Additional context

I'm installing the latest version of the package `7.0.1`, but I see another version here: https://www.npmjs.com/package/@storybook/addon-queryparams/v/6.0.0-beta.44

That uses a `withQuery` decorator. Does that matter at all? I'm on `storybook` `7.0.26`.

**Comment by yannbf** [comment]
Hey @JesseKuntz!  The hooks from Next.js won't work with this addon, as they need internal context to be passed to Nextjs.

However, if you are using Nextjs, then you should be using the @storybook/nextjs framework. That means you can use [specific parameters built in](https://storybook.js.org/docs/get-started/nextjs#overriding-defaults) in that package to mock the query parameter, for instance:

```ts
export const Example: Story = {
  parameters: {
    nextjs: {
      navigation: {
        pathname: '/profile',
        query: {
          user: '1',
        },
      },
    },
  },
};
```
